CREATE TABLE Donations(
	ID_DONATION INTEGER NOT NULL PRIMARY KEY,
	TYPE_DONATION VARCHAR(30),
	FORME_DONATION VARCHAR(30),
	VALEUR_DONATION TEXT,
	DATE_DONATION DATE,
	OBSERVATION_DONATION TEXT,
	ID_DONATEUR INTEGER
);

CREATE TABLE Donateurs(
	ID_DONATEUR INTEGER,
	NOM_DONATION VARCHAR(50),
	PRENOM_DONATEUR VARCHAR(50)
);

/* --------------------------------------------- */

CREATE TABLE Orphelins(
	ID_ORPHELIN INTEGER PRIMARY KEY,
	NOM_ORPHELIN VARCHAR(50),
	PRENOM_ORPHELIN VARCHAR(50),
	DDN_ORPHELIN DATE,
	GENRE_ORPHELIN VARCHAR(10),
	OBSERVATION_ORPHELIN TEXT,
	ID_TUTEUR INTEGER,
	RELATION_TUTEUR VARCHAR(50),
	AUTORISE BOOLEAN DEFAULT FALSE
);

CREATE TABLE DossiersFamilliaux(
	ID_DOSSIER_FAMILIAL INTEGER NOT NULL PRIMARY KEY,
	TYPE_ORPHELINAT VARCHAR(50),
	NOM_PERE VARCHAR(50),
	PRENOM_PERE VARCHAR(50),
	NOM_MERE VARCHAR(50),
	PRENOM_MERE VARCHAR(50),
	ID_ORPHELIN INTEGER
);

CREATE TABLE DossiersScolaires(
	ID_DOSSIER_SCOLAIRE INTEGER PRIMARY KEY,
	NIVEAU_SCOLAIRE VARCHAR(50),
	ANNEE_SCOLAIRE INTEGER,
	SCOLARISE BOOLEAN,
	DDMAJ DATE,
	ID_ORPHELIN INTEGER,
	OBSERVATION TEXT
);

CREATE TABLE DossiersMedicauxOrphelins(
	ID_DOSSIER_MEDICAL INTEGER NOT NULL PRIMARY KEY,
	PATHOLOGIE TEXT,
	MEDICAMENTS TEXT,
	ID_ORPHELIN INTEGER
);

CREATE TABLE Appareillages(
	ID_APPAREILLAGE INTEGER NOT NULL PRIMARY KEY,
	TYPE_APPAREILLAGE VARCHAR(50)
);

CREATE TABLE Orphelins_Appareillages(
	ID_DOSSIER_MEDICAL INTEGER NOT NULL,
	ID_APPAREILLAGE INTEGER NOT NULL
);

CREATE TABLE ApparencesPhysiques(
	ID_APPARENCE_PHYSIQUE INTEGER NOT NULL PRIMARY KEY,
	POINTURE VARCHAR(50),
	DDMAJ DATE,
	OBSERVATION_PHYSIQUE TEXT,
	ID_ORPHELIN INTEGER
);

/* ------------------------------------------------------ */

CREATE TABLE Benevoles(
	ID_BENEVOLE INTEGER NOT NULL PRIMARY KEY,
	NOM_BENEVOLE VARCHAR(50),
	PRENOM_BENEVOLE VARCHAR(50),
	GENRE VARCHAR(10),
	TELEPHONE VARCHAR(20),
	EMAIL VARCHAR(30),
	FACEBOOK VARCHAR(70)
);

CREATE TABLE JourneesDisponibles(
	ID_JOURNEE_DISPONIBLE INTEGER NOT NULL PRIMARY KEY,
	JOUR_SEMAINE VARCHAR(20),
	HEURE_DEBUT TIME,
	HEURE_FIN TIME,
	ID_BENEVOLE INTEGER
);

CREATE TABLE Vehicules(
	ID_VEHICULE INTEGER NOT NULL PRIMARY KEY,
	TYPE_VEHICULE VARCHAR(50)
);

CREATE TABLE Benevoles_Vehicules(
	ID_BENEVOLE INTEGER NOT NULL,
	ID_VEHICULE INTEGER NOT NULL
);

/* ------------------------------------------------------- */

CREATE TABLE Tuteurs(
	ID_TUTEUR INTEGER NOT NULL PRIMARY KEY,
	NOM_TUTEUR VARCHAR(50),
	PRENOM_TUTEUR VARCHAR(50),
	NOM_PERE_ORPHELINS VARCHAR(50),
	PRENOM_PERE_ORPHELINS VARCHAR(50),
	DDN_TUTEUR DATE,
	ADRESSE_TUTEUR VARCHAR(200),
	SECONDE_ADRESSE_TUTEUR VARCHAR(200),
	NCNI_TUTEUR VARCHAR(100),
	NUMERO_TELEPHONE_FIXE_TUTEUR VARCHAR(20),
	NUMERO_TELEPHONE_MOBILE_TUTEUR VARCHAR(20),
	AUTRE_NUMERO_TELEPHONE_1 VARCHAR(20),
	AUTRE_NUMERO_TELEPHONE_2 VARCHAR(20),
	ID_REGION_TUTEUR INTEGER,
	NCCP_TUTEUR VARCHAR(100),
	NCARTE_BANQUAIRE VARCHAR(100),
	NDOSSIER_BUREAUTIQUE VARCHAR(100),
	NB_ORPHELIN INTEGER,
	OBSERVATION TEXT
);

CREATE TABLE Habitats(
	ID_HABITAT INTEGER NOT NULL PRIMARY KEY,
	ETAT_HABITAT VARCHAR(50),
	TYPE_BIEN VARCHAR(50),
	CLASSEMENT_HABITAT TEXT,
	ID_TUTEUR INTEGER
);

CREATE TABLE DossiersMedicauxTuteurs(
	ID_DOSSIER_MEDICAL INTEGER NOT NULL PRIMARY KEY,
	PATHOLOGIE TEXT,
	MEDICAMENTS TEXT,
	ID_TUTEUR INTEGER
);

CREATE TABLE Tuteurs_Appareillages(
	ID_DOSSIER_MEDICAL INTEGER NOT NULL,
	ID_APPAREILLAGE INTEGER NOT NULL
);

CREATE TABLE SituationsSociales(
	ID_SITUATION_SOCIALE INTEGER NOT NULL PRIMARY KEY,
	NIVEAU_VIE VARCHAR(50),
	FONCTION VARCHAR(50),
	RETRAIRE REAL,
	CONVERTURE_SOCIALE REAL,
	SALAIRE REAL,
	NIVEAU_ETUDE VARCHAR(50),
	COMPETANCES TEXT,
	ID_TUTEUR INTEGER
);

CREATE TABLE Enquetes(
	ID_ENQUETE INTEGER NOT NULL PRIMARY KEY,
	NOM_ENQUETEUR VARCHAR(50),
	PRENOM_ENQUETEUR VARCHAR(50),
	DATE_ENQUETE DATE,
	ID_SITUATION_SOCIALE INTEGER
);

CREATE TABLE Regions(
	ID_REGION INTEGER NOT NULL PRIMARY KEY,
	NOM_REGION VARCHAR(100)
);

/* ----------------------------------------- Evennements ------------------------------------------ */

CREATE TABLE EVENEMENTS_LOTS(
	ID_EVENEMENT INTEGER NOT NULL PRIMARY KEY,
	DESIGNATION_EVENEMENT TEXT,
	DESCRIPTION_EVENEMENT TEXT,
	DATE_EVENEMENT DATE
);

CREATE TABLE EVENEMENTS_BONS(
	ID_EVENEMENT INTEGER NOT NULL PRIMARY KEY,
	DESIGNATION_EVENEMENT TEXT,
	DESCRIPTION_EVENEMENT TEXT,
	DATE_EVENEMENT DATE,
	COUT_BON REAL,
	ETABLISSEMENT_VALIDATION TEXT
);

CREATE TABLE ACTIONS(
	ID_ACTION INTEGER NOT NULL PRIMARY KEY,
	DATE_ACTION DATE,
	QUANTITE_ACTION INTEGER,
	ID_TUTEUR INTEGER,
	ID_EVENEMENT INTEGER
);

/* --------------------------------------- INDEXES ----------------------------------------------- */

CREATE UNIQUE INDEX IND_ID_VEHICULE ON VEHICULES(ID_VEHICULE);
CREATE UNIQUE INDEX IND_ID_REGION ON REGIONS(ID_REGION);
CREATE UNIQUE INDEX IND_ID_HABITAT ON HABITATS(ID_TUTEUR);
CREATE UNIQUE INDEX IND_ID_DOSSIER_MEDICAL_TUTEUR ON DOSSIERSMEDICAUXTUTEURS(ID_TUTEUR);
CREATE UNIQUE INDEX IND_ID_DOSSIER_MEDICAL_ORPHELIN ON DOSSIERSMEDICAUXORPHELINS(ID_ORPHELIN);
CREATE UNIQUE INDEX IND_ID_SITUATION_SOCIALE ON SITUATIONSSOCIALES(ID_TUTEUR);
CREATE UNIQUE INDEX IND_ID_ENQUETE ON ENQUETES(ID_SITUATION_SOCIALE);
CREATE UNIQUE INDEX IND_ID_EVENEMENT_BON ON EVENEMENTS_BONS(ID_EVENEMENT);
CREATE UNIQUE INDEX IND_ID_EVENEMENT_LOT ON EVENEMENTS_LOTS(ID_EVENEMENT);
CREATE UNIQUE INDEX IND_ID_TUTEUR ON TUTEURS(ID_TUTEUR);
CREATE UNIQUE INDEX IND_ID_DOSSIER_FAMILLIAL ON DOSSIERSFAMILLIAUX(ID_ORPHELIN);
CREATE UNIQUE INDEX IND_ID_APPARENCE_PHYSIQUE ON APPARENCESPHYSIQUES(ID_ORPHELIN);
CREATE UNIQUE INDEX IND_ID_DOSSIER_SCOLAIRE ON DOSSIERSSCOLAIRES(ID_ORPHELIN);
CREATE UNIQUE INDEX IND_ID_ORPHELIN ON ORPHELINS(ID_ORPHELIN);

CREATE INDEX IND_ID_DONATION ON DONATIONS(ID_DONATEUR);

CREATE INDEX IND_DDN_OPRHELIN ON ORPHELINS(DDN_ORPHELIN);
